#!/bin/sh

./gradlew clean
./gradlew build
./gradlew --console=verbose publishToMavenLocal

./gradlew textdrawable:javaDocReleaseJar
cp textdrawable/build/intermediates/java_doc_jar/release/release-javadoc.jar ~/.m2/repository/io/github/mores/textdrawable/1.0.1/textdrawable-1.0.1-javadoc.jar

./gradlew textdrawable:sourceReleaseJar
cp textdrawable/build/intermediates/source_jar/release/release-sources.jar ~/.m2/repository/io/github/mores/textdrawable/1.0.1/textdrawable-1.0.1-sources.jar

cd ~/.m2/repository/io/github/mores/textdrawable/1.0.1/

FILES="textdrawable-1.0.1-javadoc.jar textdrawable-1.0.1-sources.jar textdrawable-1.0.1.pom textdrawable-1.0.1.aar"

for FILE in $FILES
do
	md5sum --quiet $FILE > $FILE.md5
	sha1sum --quiet $FILE > $FILE.sha1
done

gpg -ab textdrawable-1.0.1.aar
gpg -ab textdrawable-1.0.1.pom
gpg -ab textdrawable-1.0.1-javadoc.jar
gpg -ab textdrawable-1.0.1-sources.jar

cd ~/.m2/repository
zip /tmp/textdrawable-1.0.1.zip io/github/mores/textdrawable/1.0.1/*

cd -

#upload to https://central.sonatype.com/publishing/deployments

